// flow-typed signature: a05a8f58da48bac3d7389bab3b0ef3d5
// flow-typed version: <<STUB>>/camelize_v^1.0.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'camelize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'camelize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'camelize/example/camel' {
  declare module.exports: any;
}

declare module 'camelize/test/camel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'camelize/example/camel.js' {
  declare module.exports: $Exports<'camelize/example/camel'>;
}
declare module 'camelize/index' {
  declare module.exports: $Exports<'camelize'>;
}
declare module 'camelize/index.js' {
  declare module.exports: $Exports<'camelize'>;
}
declare module 'camelize/test/camel.js' {
  declare module.exports: $Exports<'camelize/test/camel'>;
}
