// flow-typed signature: fe29e684baacdec522fe01b707bc027a
// flow-typed version: <<STUB>>/rosie_v^2.0.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rosie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rosie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rosie/src/rosie' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rosie/src/rosie.js' {
  declare module.exports: $Exports<'rosie/src/rosie'>;
}
