// flow-typed signature: 46e141d84474428bfd7bcb010eacb157
// flow-typed version: <<STUB>>/universal-cookie_v^3.0.4/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'universal-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'universal-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'universal-cookie/cjs/Cookies' {
  declare module.exports: any;
}

declare module 'universal-cookie/cjs/index' {
  declare module.exports: any;
}

declare module 'universal-cookie/cjs/types' {
  declare module.exports: any;
}

declare module 'universal-cookie/cjs/utils' {
  declare module.exports: any;
}

declare module 'universal-cookie/es6/Cookies' {
  declare module.exports: any;
}

declare module 'universal-cookie/es6/index' {
  declare module.exports: any;
}

declare module 'universal-cookie/es6/types' {
  declare module.exports: any;
}

declare module 'universal-cookie/es6/utils' {
  declare module.exports: any;
}

declare module 'universal-cookie/lib/Cookies' {
  declare module.exports: any;
}

declare module 'universal-cookie/lib/index' {
  declare module.exports: any;
}

declare module 'universal-cookie/lib/types' {
  declare module.exports: any;
}

declare module 'universal-cookie/lib/utils' {
  declare module.exports: any;
}

declare module 'universal-cookie/umd/universalCookie' {
  declare module.exports: any;
}

declare module 'universal-cookie/umd/universalCookie.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'universal-cookie/cjs/Cookies.js' {
  declare module.exports: $Exports<'universal-cookie/cjs/Cookies'>;
}
declare module 'universal-cookie/cjs/index.js' {
  declare module.exports: $Exports<'universal-cookie/cjs/index'>;
}
declare module 'universal-cookie/cjs/types.js' {
  declare module.exports: $Exports<'universal-cookie/cjs/types'>;
}
declare module 'universal-cookie/cjs/utils.js' {
  declare module.exports: $Exports<'universal-cookie/cjs/utils'>;
}
declare module 'universal-cookie/es6/Cookies.js' {
  declare module.exports: $Exports<'universal-cookie/es6/Cookies'>;
}
declare module 'universal-cookie/es6/index.js' {
  declare module.exports: $Exports<'universal-cookie/es6/index'>;
}
declare module 'universal-cookie/es6/types.js' {
  declare module.exports: $Exports<'universal-cookie/es6/types'>;
}
declare module 'universal-cookie/es6/utils.js' {
  declare module.exports: $Exports<'universal-cookie/es6/utils'>;
}
declare module 'universal-cookie/lib/Cookies.js' {
  declare module.exports: $Exports<'universal-cookie/lib/Cookies'>;
}
declare module 'universal-cookie/lib/index.js' {
  declare module.exports: $Exports<'universal-cookie/lib/index'>;
}
declare module 'universal-cookie/lib/types.js' {
  declare module.exports: $Exports<'universal-cookie/lib/types'>;
}
declare module 'universal-cookie/lib/utils.js' {
  declare module.exports: $Exports<'universal-cookie/lib/utils'>;
}
declare module 'universal-cookie/umd/universalCookie.js' {
  declare module.exports: $Exports<'universal-cookie/umd/universalCookie'>;
}
declare module 'universal-cookie/umd/universalCookie.min.js' {
  declare module.exports: $Exports<'universal-cookie/umd/universalCookie.min'>;
}
