#
# CircleCI Build Script
# Install the CLI from https://circleci.com/docs/2.0/local-cli/
# So you can run `circleci config validate`
# Needs following envars setup:
#   - AWS_ACCESS_KEY_ID
#   - AWS_SECRET_ACCESS_KEY
#   - SENTRY_AUTH_TOKEN
version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:3.6.9-node-browsers
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-v1-{{ checksum "yarn.lock" }}
            - deps-v1-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: deps-v1-{{ checksum "yarn.lock" }}
      - run: ./scripts/circleci/build.sh
      - run: ./scripts/circleci/setup-awscli.sh
      - run: ./scripts/circleci/deploy.sh

workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy:
          filters: { branches: { only: [master, develop] } }
