export const FIELD_TYPES = {
  DROPDOWN: 'DROPDOWN',
  MULTICHOICE: 'MULTICHOICE',
  TEXTAREA: 'TEXTAREA',
  FILE: 'FILE',
  DATE: 'DATE',
  BOOLEAN: 'BOOLEAN',
  TEXT: 'TEXT',
  NUMBER: 'NUMBER',
  DOLLAR: 'DOLLAR',
}
