// @flow
export const FIELD_TYPES = {
  DISPLAY: 'DISPLAY',
  TEXT: 'TEXT',
  EMAIL: 'EMAIL',
  NUMBER: 'NUMBER',
  DATE: 'DATE',
  CHOICE_SINGLE: 'CHOICE_SINGLE',
  CHOICE_MULTI: 'CHOICE_MULTI',
  FILE: 'FILE',
  PHOTO: 'PHOTO',
}
