// @flow
export const FIELD_TYPES: { [string]: string } = {
  FIELD_GROUP: 'FIELD_GROUP',
  DROPDOWN: 'DROPDOWN',
  MULTI_SELECT: 'MULTI_SELECT',
  RADIO: 'RADIO',
  RADIO_BTN: 'RADIO_BTN',
  TEXTAREA: 'TEXTAREA',
  FILE: 'FILE',
  DATE: 'DATE',
  BOOLEAN: 'BOOLEAN',
  TEXT: 'TEXT',
  NUMBER: 'NUMBER',
  DOLLAR: 'DOLLAR',
}
