name: Deploy
on:
  - workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo from GitHub
      - uses: actions/checkout@v2

      # Setup transcrypt so that we can read secrets
      - name: Checkout transcrypt
        uses: actions/checkout@v2
        with:
          repository: elasticdog/transcrypt
          path: transcrypt

      - name: Initialise transcrypt
        run: ./transcrypt/transcrypt -c aes-256-cbc -p '${{ secrets.TRANSCRYPT_PASSWORD }}' --yes

      # Install AWS CLI
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.3

      # Install node modules
      - name: Install node modules
        run: yarn install

      # Build and deploy
      - name: Run deploy script
        shell: bash
        env:
          # I don't know why we need this but AWS CLI breaks without it.
          AWS_EC2_METADATA_DISABLED: true
        run: |
          if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            ./scripts/release/staging.sh
          elif [ "${{ github.ref }}" = "refs/heads/master" ]; then
            ./scripts/release/prod.sh
          else
            echo "Please specify either the develop branch for staging or master branch for prod"
            exit 1
          fi
