name: Deploy
on:
  - workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo from GitHub
      - uses: actions/checkout@v2

      # Setup transcrypt so that we can read secrets
      - name: Checkout transcrypt
        uses: actions/checkout@v2
        with:
          repository: elasticdog/transcrypt
          path: transcrypt

      - name: Initialise transcrypt
        run: ./transcrypt/transcrypt -c aes-256-cbc -p '${{ secrets.TRANSCRYPT_PASSWORD }}' --yes

      # Install node modules
      - name: Install node modules
        run: yarn install

      # Build and deploy
      - name: Run deploy script
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            ./scripts/release/test.sh
          elif [ "${{ github.ref }}" = "refs/heads/master" ]; then
            ./scripts/release/prod.sh
          else
            echo "Please specify either the develop branch for staging or master branch for prod"
            exit 1
          fi
